/** Copy & structure from byosync-landing (lib/content.ts) — single source for marketing sections */

export const LANDING_HERO = {
  eyebrow: "New Trust stack · Early access",
  headline: "One integration.\nThe full trust stack.",
  subline:
    "ByoSync helps companies find risky data flows, reduce user-data custody, and prove that a real human approved every sensitive action.",
  supporting: "UPI made money movement instant. ByoSync makes human trust instant.",
  proofStrip: [
    "Private vault",
    "Tokenized access",
    "Live human approval",
    "Revoke webhook",
    "Audit evidence",
  ],
};

export const LANDING_PROBLEM = {
  eyebrow: "The gap nobody talks about",
  headline:
    "Companies collect too much user data, but still cannot prove who approved its use.",
  cards: [
    {
      title: "Credentials can be faked.",
      body: "OTPs, passwords, documents, and checkboxes can be stolen, replayed, shared, or generated by bots and deepfakes.",
    },
    {
      title: "KYC is a one-time snapshot.",
      body: "It proves who someone was once, not that a live human approved this exact action, purpose, and data field today.",
    },
    {
      title: "Compliance evidence is scattered.",
      body: "Consent, logs, deletion, vendor sharing, and breach evidence live across disconnected tools — hard to produce, harder to prove.",
    },
    {
      title: "Data custody keeps growing.",
      body: "Companies store more sensitive user data than they need, making them high-value targets with high breach exposure.",
    },
  ],
  bottomLine:
    "Missing layer: live human + purpose + data fields + expiry + revocation + audit proof.",
};

export const LANDING_SOLUTION = {
  headline: "One integration. The full trust stack.",
  subline:
    "ByoSync reduces data custody and proves that a real human — not an AI — approved the exact action, purpose, and data access.",
  layers: [
    {
      id: 1,
      label: "Trust Integration Agent",
      desc: "Scans flows · finds gaps · suggests SDK/API integration",
    },
    {
      id: 2,
      label: "Vault + Token Layer",
      desc: "Private vault · tokenized access · less raw PII",
    },
    {
      id: 3,
      label: "Human Approval Layer",
      desc: "Face + voice + device-bound live intent",
    },
    {
      id: 4,
      label: "Proof + Revocation Layer",
      desc: "Proof token · consent receipt · revoke webhook",
    },
    {
      id: 5,
      label: "Evidence Dashboard",
      desc: "Audit logs · access history · breach-impact mapping",
    },
  ],
  ctoBox:
    "SDK/API · vault · tokenized access · live approval · proof token · revoke webhook · audit evidence",
};

export const LANDING_HOW_IT_WORKS = {
  headline: "How a trust event works",
  steps: [
    {
      id: 1,
      title: "Partner asks",
      desc: "Login, payout, consent, recovery, delivery proof, or data access",
      tag: "trigger",
    },
    {
      id: 2,
      title: "ByoSync creates challenge",
      desc: "User + partner + purpose + fields + expiry + nonce bound together",
      tag: "challenge",
    },
    {
      id: 3,
      title: "User reviews intent",
      desc: "Company, purpose, amount/data fields, expiry — crystal clear",
      tag: "review",
    },
    {
      id: 4,
      title: "Live approval",
      desc: "Face + voice + liveness + device binding — not a checkbox",
      tag: "approve",
    },
    {
      id: 5,
      title: "Proof generated",
      desc: "Purpose-bound proof token with full context",
      tag: "proof",
    },
    {
      id: 6,
      title: "Partner stores audit event",
      desc: "Proof token + event log. No raw PII at partner by default.",
      tag: "audit",
    },
  ],
  io: {
    input: ["user", "company", "action", "purpose", "fields", "expiry", "nonce"],
    output: ["proof token", "consent receipt", "audit log", "revoke webhook"],
  },
};

export const LANDING_BEFORE_AFTER = {
  headline: "Before and after ByoSync",
  before: [
    "Many vendors, multiple API bills",
    "Raw PII in partner database",
    "Manual consent logs",
    "Weak revocation paths",
    "Scattered audit evidence",
    "No proof of live human intent",
  ],
  after: [
    "One trust runtime",
    "Private vault, tokenized access",
    "Human-approved actions",
    "Revoke webhook",
    "Evidence dashboard",
    "Purpose-bound proof token",
  ],
};

export const LANDING_PROOF = {
  headline: "Traction",
  stats: [
    { label: "IIT Mandi iHub", value: "SISFS ₹20L", sub: "Grant" },
    { label: "ISB IVY", value: "Cohort 4", sub: "Accelerator" },
    { label: "Indian Patent", value: "Filed Aug 2025", sub: "Pending" },
    { label: "Users Tested", value: "4,000+", sub: "Beta" },
    { label: "FAR", value: "<0.001%", sub: "Liveness" },
    { label: "Flow Latency", value: "<4s", sub: "End-to-end" },
  ],
  note: "Pilot/prototype-stage metrics, continuing validation in live deployments.",
};

export const LANDING_FINAL_CTA = {
  headline: "Build trust into the workflow,\nnot after the audit.",
  subline:
    "ByoSync creates proof inside the product flow: who approved, what purpose, which data, what expiry, and when it can be revoked.",
  legalNote:
    "ByoSync helps implement and evidence controls. Final compliance depends on customer scope, deployment, and audit.",
};
